import { dbSeries } from "./dataBase.js";
dbSeries.show_seriesList();
dbSeries.show_serieDetails("Stranger Things");
dbSeries.show_categories();
dbSeries.show_actorsAndDirectorsListOfSerie("Stranger Things");
dbSeries.show_actorDetails("Millie Bobby");
dbSeries.show_directorDetails("Shawn Levy");
dbSeries.show_plataformas();
dbSeries.show_PlataformaDetails("Netflix");
dbSeries.show_PlataformaDetails("Amazon Prime Video");
// dbSeries.show_serieDetails("Kitmetsu no Yaiba");
